import turtle

class ViewMatrix:
    screen = turtle.Screen()
    screen.bgcolor('gray')
    turtle.title('World Wumpus in python with lib turtle')

    matrix = turtle.Turtle()
    matrix.shape('turtle')
    matrix.color('lightgray')
    matrix.penup()
    matrix.goto(-200, 200)
    matrix.pensize(2.5)
    matrix.pencolor('black')

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(-100, 200)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(0, 200)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(100, 200)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(200, 200)
    matrix.goto(-200, 100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(-100, 100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(0, 100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(100, 100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(200, 100)
    matrix.goto(-200, 0)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(-100, 0)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(0, 0)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(100, 0)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(200, 0)
    matrix.goto(-200, -100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(-100, -100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(0, -100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(100, -100)

    matrix.pendown()
    matrix.begin_fill()
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.forward(100)
    matrix.right(90)
    matrix.end_fill()

    matrix.penup()
    matrix.goto(200, -100)
    matrix.goto(-200, 200)

    turtle.done()